### ISSUE TITLE
Flutter 3 WidgetsBinding Issue

### ISSUE THREAD

**Issue by noga-dev** [marcglasberg/back_button_interceptor#17]
#16 

For now add this to pubspec;

```yaml
dependency_overrides:
  back_button_interceptor:
    git:
      url: https://github.com/noga-dev/back_button_interceptor.git
      ref: a1f3031251ea86978f21a4d86db92da0700568dd
```
